# ! JUST READ - don't change the content of this file
# Server settings with YAML header values and defaults
use_cookies: no
auto_scroll: no
rate_survey: no
all_questions_required: yes
system_language: en
highlight_unanswered: yes
highlight_color: blue
capture_metadata: yes

